remote_theme: yous/whiteglass
title: prescient
description: Simulation of single cell differentiation trajectories using longitudinal scRNA-seq.
repository: gifford-lab/prescient
show_downloads: false
markdown: GFM
navbar_items:
  - title: Home
    url: /
  - title: Documentation
    url: /documentation
  - title: Input formats
    url: /input_formats
  - title: Vignettes
    url: /analysis
  - title: Paper
    url: /paper
