remote_theme: yous/whiteglass
title: prescient
description: Simulation of single cell differentiation trajectories using longitudinal scRNA-seq.
repository: gifford-lab/prescient
show_downloads: false
navbar_items:
  - title: Home
    url: /
  - title: Documentation
    url: /documentation
  - title: Input formats
    url: /input_formats
  - title: Vignettes
    url: /analysis
  - title: Paper
    url: /paper

atom:
  buildCommand:
    - jekyll
    - build
    - --option
    - --this
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _drafts
